name: Deploy to Server Moi

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn deploy
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute deployment commands on remote server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22  # Hoặc cổng SSH tùy chỉnh nếu bạn dùng
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 20.18.3
            
            cd /var/www/ads_v2/fe-ads-manager-v2
            git pull
            npm i --force
            npm run build
            pm2 reload "ads-fe-manager-v2"
